# この項目を手動で書き換えないでください。
schedules:
  d863cee6-c381-4255-87a5-1ef17cf041e9:
    next-date-time: '2011-12-03T10:15:30+09:00[Asia/Tokyo]'
    interval:
      value: 1
      unit: Minute
    seed-pattern: CurrentSeed
    worlds:
      - world
      - world_TEST

settings:
  teleport-world-name: world
  command:
    before:
      - say %world%の再生成を開始します。
    after:
      - say %world%の再生成を終了しました。運営チームからのアナウンスがあるまでワールドに入場しないでください。