name: @name@
version: @version@
main: click.seichi.regenerateworld.presenter.RegenerateWorld
depend: [ Multiverse-Core ]
commands:
  regenerateworld:
    usage: /rw
    aliases:
      - regenworld
      - rw
    description: This is the command for RegenerateWorld.
    default: op