name: RegenerateWorld
version: 0.1.0
main: click.seichi.regenerateworld.RegenerateWorld
depend: [ Multiverse-Core ]
commands:
  regenerateworld:
    usage: /rw
    aliases:
      - regenworld
      - rw
    description: This is the command for RegenerateWorld.
    default: op