name: CI
on:
  push:
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/workflows/ci-and-cd.yml
  pull_request:
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/workflows/ci-and-cd.yml

jobs:
  ci:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    env:
      BUILD_ENVIRONMENT_IS_CI_OR_LOCAL: CI
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java and Cache deps
        uses: ./.github/actions/setup-build

      - name: Check format with Scalafmt
        run: sbt scalafmtCheckAll
      - name: Check lint with Scalafix
        run: sbt "scalafix --check"
      - name: Test
        run: sbt test
      - name: Build artifact
        run: sbt assembly

      - name: Clean build artifact for caching target folder
        run: rm -r target/build
  cd:
    name: Release
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java and Cache deps
        uses: ./.github/actions/setup-build

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.14.0
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
#          output-file: 'false'
          release-count: 1
          preset: 'eslint'
          skip-version-file: 'true'
          git-push: 'false'
      - name: Build artifact
        run: sbt assembly
      - name: Debug step
        run: |
          git tag
          git --no-pager log --pretty=oneline -n1
          ls target/build
          cat CHANGELOG.md
      - name: Clean build artifact for caching target folder
        run: rm -r target/build
